apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  selector:
    app: {{ .Values.mysql.name }}
    tier: {{ .Values.mysql.tier }}
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
