apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: {{ .Values.wordpress.name }}
    tier: frontend
  ports:
    - port: {{ .Values.wordpress.service.port }}
  type: {{ .Values.wordpress.service.type }}
